# Generated by Django 2.0.7 on 2018-07-09 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='limit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
