# Generated by Django 2.0.7 on 2018-07-09 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20180709_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='sign',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
